import { WidgetConfig } from 'src/store/reducer/dashboardWidgets.slice';

export const allDashboardWidgets: WidgetConfig[] = [
  {
    id: 'widget-1',
    title: 'Turn Over Details',
    description: 'Monthly trade turnover in bar chart visualization',
    langKey: 'widget.turnover',
    color: '#FDE2FF',
  },
  {
    id: 'widget-2',
    title: 'Executed Order Count / Value',
    description: 'Monthly executed order data by count and value',
    langKey: 'widget.executedOrder',
    color: '#D8EAFE',
  },
  {
    id: 'widget-3',
    title: 'Top Ten Customers',
    description: 'Top-performing customers by volume and value',
    langKey: 'widget.topCustomers',
    color: '#D9F8DA',
  },
  {
    id: 'widget-4',
    title: 'High Touch vs Low Touch',
    description: 'Distribution of High Touch (DT) vs Low Touch (Online)',
    langKey: 'widget.touchComparison',
    color: '#FEE0DC',
  },
  {
    id: 'widget-5',
    title: 'Brokerage Commission Income',
    description: 'Brokerage-based commission income overview',
    langKey: 'widget.brokerageIncome',
    color: '#FFD9E0',
  },
  {
    id: 'widget-6',
    title: 'New Customers Onboard',
    description: 'Monthly new customer onboard stats',
    langKey: 'widget.newCustomers',
    color: '#D7F7F3',
  },
  {
    id: 'widget-7',
    title: 'New Portfolios Created',
    description: 'Total new portfolios created during the month',
    langKey: 'widget.newPortfolios',
    color: '#FDFCCF',
  },
  {
    id: 'widget-8',
    title: 'New Margin Accounts',
    description: 'Monthly margin account openings stats',
    langKey: 'widget.newMargin',
    color: '#C7F9EF',
  },
  {
    id: 'widget-9',
    title: 'Avg Order Size',
    description: 'Average order size in value for the month',
    langKey: 'widget.avgOrderSize',
    color: '#F3D9FF',
  },
  {
    id: 'widget-10',
    title: 'Client Trade Frequency',
    description: 'Average number of trades per client',
    langKey: 'widget.tradeFrequency',
    color: '#DCF7FD',
  },
  {
    id: 'widget-11',
    title: 'Total Market Turnover',
    description: 'Total market turnover on selected period',
    langKey: 'widget.totalMarketTurnover',
    color: '#FFF5D9',
  },
  {
    id: 'widget-12',
    title: 'Top Ten Stocks by Value',
    description: 'Top 10 traded stocks by value',
    langKey: 'widget.topStocksValue',
    color: '#FFDDD2',
  },
  {
    id: 'widget-13',
    title: 'Top Ten Stocks by Volume',
    description: 'Top 10 traded stocks by volume',
    langKey: 'widget.topStocksVolume',
    color: '#CCE8FF',
  },
  {
    id: 'widget-14',
    title: 'Total Trades Executed',
    description: 'Overall number of trades executed this month',
    langKey: 'widget.totalTrades',
    color: '#E1FFDD',
  },
  {
    id: 'widget-15',
    title: 'Broker Ranking by Value',
    description: 'Rank of your brokerage by trade value',
    langKey: 'widget.brokerRankingValue',
    color: '#FFE0F0',
  },
  {
    id: 'widget-16',
    title: 'Broker Ranking by Volume',
    description: 'Rank of your brokerage by trade volume',
    langKey: 'widget.brokerRankingVolume',
    color: '#D0ECFF',
  },
  {
    id: 'widget-17',
    title: 'Mobile vs Web Trade Split',
    description: 'Breakdown of trades done via mobile vs web',
    langKey: 'widget.tradeSplitPlatform',
    color: '#FFEACC',
  },
  {
    id: 'widget-18',
    title: 'Market Share by Sector',
    description: 'Trading market share comparison across sectors',
    langKey: 'widget.marketShareSector',
    color: '#E6FFDA',
  },
];
